import { prisma } from "../src/lib/prisma.ts";
import { TicketStatus, TicketCategory } from "../generated/prisma/enums.ts";

const tickets: Array<{
  subject: string;
  body: string;
  fromName: string;
  fromEmail: string;
  status: TicketStatus;
  category: TicketCategory | null;
  createdAt: Date;
}> = [
  // Refund requests
  {
    subject: "Request for refund on order #84921",
    body: "Hi, I placed an order last week but the item arrived damaged. I'd like a full refund please. Order number is #84921.",
    fromName: "Sarah Mitchell",
    fromEmail: "sarah.mitchell@gmail.com",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(1),
  },
  {
    subject: "Double charged on my account",
    body: "I was charged twice for the same subscription this month. Please refund the duplicate charge of $49.99.",
    fromName: "James Kowalski",
    fromEmail: "j.kowalski@outlook.com",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(2),
  },
  {
    subject: "Cancelled subscription still being billed",
    body: "I cancelled my plan three weeks ago but I'm still seeing charges on my card. This needs to stop immediately.",
    fromName: "Priya Nair",
    fromEmail: "priya.nair@yahoo.com",
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(5),
  },
  {
    subject: "Wrong product delivered — need refund",
    body: "I ordered the blue version but received the red one. I don't want an exchange, just a refund.",
    fromName: "Tom Hargreaves",
    fromEmail: "tom.h@protonmail.com",
    status: TicketStatus.closed,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(14),
  },
  {
    subject: "Annual plan refund — moving to competitor",
    body: "We've decided to move to another platform. We're 2 months into an annual plan and would like a pro-rated refund for the remaining 10 months.",
    fromName: "Daniel Reyes",
    fromEmail: "daniel.reyes@techcorp.io",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(0),
  },
  {
    subject: "Refund for unused credits",
    body: "We purchased a credit bundle 6 months ago and still have 3,400 credits remaining. Can we get a refund for those?",
    fromName: "Fatima Al-Hassan",
    fromEmail: "fatima@designstudio.ae",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(3),
  },
  {
    subject: "Service outage during event — refund request",
    body: "Your platform was down for 4 hours during our live product launch. This caused significant revenue loss. We are requesting a full month refund.",
    fromName: "Marcus Johansson",
    fromEmail: "marcus.j@eventco.se",
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(7),
  },
  {
    subject: "Charged after free trial ended",
    body: "I was supposed to be on a free trial but I see a charge on my statement. I never agreed to upgrade to a paid plan.",
    fromName: "Chloe Dupont",
    fromEmail: "chloe.dupont@gmail.com",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(1),
  },
  {
    subject: "Refund request — accidental purchase",
    body: "My 8-year-old used my phone and accidentally purchased the premium plan. I only just noticed the charge. Please refund.",
    fromName: "Raj Patel",
    fromEmail: "raj.patel@hotmail.com",
    status: TicketStatus.closed,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(20),
  },
  {
    subject: "Overcharged for enterprise tier",
    body: "Our invoice shows $2,400 but we were quoted $1,800. Please review and issue a credit for the difference.",
    fromName: "Natalie Bergström",
    fromEmail: "natalie@nordicfinance.se",
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(9),
  },

  // Technical questions
  {
    subject: "API rate limit keep getting hit",
    body: "We're hitting the 1000 req/min rate limit even though our usage dashboard shows we're well under. Is there a burst limit we should know about?",
    fromName: "Aisha Kamara",
    fromEmail: "aisha.kamara@startupxyz.com",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "Webhook signatures failing validation",
    body: "Our HMAC validation for incoming webhooks started failing yesterday without any changes on our end. Same secret key, same code. What changed?",
    fromName: "Luca Ferretti",
    fromEmail: "luca@codelab.it",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "SSO login broken after domain migration",
    body: "We migrated our company domain from acme.org to acme.com last week and now SSO is failing for all users. Getting error: 'metadata URL mismatch'.",
    fromName: "Helen Park",
    fromEmail: "helen.park@acme.com",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(6),
  },
  {
    subject: "Data export timing out for large datasets",
    body: "When I try to export more than 50k rows the job times out after 30 seconds. Smaller exports work fine. Is there a way to do it in batches via the API?",
    fromName: "Oluwaseun Adeyemi",
    fromEmail: "seun@analyticsco.ng",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "OAuth2 redirect_uri mismatch error",
    body: "I'm integrating your OAuth2 flow and keep getting redirect_uri_mismatch even though the URI in my app settings matches exactly. Screenshot attached.",
    fromName: "Ben Carter",
    fromEmail: "ben.carter@devshop.co.uk",
    status: TicketStatus.closed,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(15),
  },
  {
    subject: "CSV import skipping rows with special characters",
    body: "When I upload a CSV with names containing accented characters (é, ü, ñ) those rows are silently skipped. Is UTF-8 encoding required?",
    fromName: "Isabel Ferreira",
    fromEmail: "isabel.f@empresa.pt",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(8),
  },
  {
    subject: "Can I self-host the analytics module?",
    body: "For compliance reasons we need all data to remain on-premise. Does your enterprise plan support self-hosted analytics or is it always cloud-based?",
    fromName: "Vikram Singh",
    fromEmail: "vikram@govtech.in",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    subject: "Mobile SDK crashing on Android 14",
    body: "Since Android 14 rolled out our users are seeing crashes in the SDK on first launch. Error: 'java.lang.NoSuchMethodException'. Running SDK v3.2.1.",
    fromName: "Yuki Tanaka",
    fromEmail: "yuki.tanaka@mobileapp.jp",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Emails not delivering to Outlook addresses",
    body: "Transactional emails work fine for Gmail users but Outlook recipients never receive them. Our SPF and DKIM are configured. Checked spam — not there either.",
    fromName: "Sandra Müller",
    fromEmail: "sandra.mueller@firma.de",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(11),
  },
  {
    subject: "Pagination broken when deleting records",
    body: "When I delete a record on page 3 and then navigate to the next page, I get duplicate entries. Looks like an off-by-one issue with cursor-based pagination.",
    fromName: "Chris O'Brien",
    fromEmail: "chris.obrien@saas.ie",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(4),
  },
  {
    subject: "2FA codes not working",
    body: "My authenticator app generates codes but they're rejected every time. I've verified my phone's clock is synced. This started after I got a new phone.",
    fromName: "Ahmed Khalil",
    fromEmail: "ahmed.khalil@email.com",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "Zapier integration not triggering",
    body: "My Zap is set to trigger on new records but it stopped firing 3 days ago. Test events work, live ones don't. Nothing changed in my setup.",
    fromName: "Megan Torres",
    fromEmail: "megan.t@marketingagency.com",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    subject: "GraphQL subscriptions disconnecting every 60s",
    body: "WebSocket connections for GraphQL subscriptions drop exactly every 60 seconds. Looks like a server-side timeout. Is there a keepalive setting I should enable?",
    fromName: "Pavel Novak",
    fromEmail: "pavel.novak@devteam.cz",
    status: TicketStatus.closed,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(22),
  },
  {
    subject: "IP allowlist not taking effect",
    body: "I added our office IP to the allowlist 2 hours ago but requests are still being blocked. Is there a propagation delay I should expect?",
    fromName: "Kwame Asante",
    fromEmail: "kwame.asante@ghanatech.gh",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(13),
  },
  {
    subject: "File upload size limit unclear",
    body: "The docs say 'files up to 100MB' but I'm hitting an error at 25MB. Is the limit per file or per request? What's the actual limit for the Pro plan?",
    fromName: "Sophie Laurent",
    fromEmail: "sophie.laurent@creativeagency.fr",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },

  // General questions
  {
    subject: "How do I add team members to my account?",
    body: "I'm on the Business plan and I'd like to invite two colleagues. Where do I go to send invitations?",
    fromName: "Robert Kim",
    fromEmail: "robert.kim@smallbiz.com",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(18),
  },
  {
    subject: "What's included in the Enterprise plan?",
    body: "We're a 500-person company evaluating options. Can you send me a breakdown of what's included in Enterprise vs Business? Specifically around SLAs and dedicated support.",
    fromName: "Amara Diallo",
    fromEmail: "amara.diallo@conglomerate.sn",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Do you offer nonprofit discounts?",
    body: "We're a registered 501(c)(3) charity. Do you have special pricing for nonprofits? We're currently on the free tier but need more features.",
    fromName: "Grace Okonkwo",
    fromEmail: "grace@ngofoundation.org",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(10),
  },
  {
    subject: "GDPR data processing agreement needed",
    body: "Our legal team requires a signed Data Processing Agreement before we can upgrade to a paid plan. Can you provide a DPA template or point me to where I can sign one?",
    fromName: "Erik Lindqvist",
    fromEmail: "erik.l@swecompany.se",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "How do I export all my data?",
    body: "I'm planning to close my account but want to export everything first. What formats are available and how long does an export take?",
    fromName: "Hana Suzuki",
    fromEmail: "hana.suzuki@freelancer.jp",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(25),
  },
  {
    subject: "Is there a desktop app?",
    body: "The web app is great but I'd love a native desktop app for offline use. Is there one available or on the roadmap?",
    fromName: "Carlos Mendoza",
    fromEmail: "carlos.mendoza@remote.mx",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(30),
  },
  {
    subject: "Changing the primary account email",
    body: "I need to update the email address on our company account from an old domain to our new one. What's the process for this?",
    fromName: "Laura Benson",
    fromEmail: "laura@oldcompany.co.uk",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(7),
  },
  {
    subject: "How do I pause my subscription?",
    body: "We're a seasonal business and don't need the service for 3 months. Is there an option to pause instead of cancel?",
    fromName: "Mohammed Al-Rashid",
    fromEmail: "mohammed.rashid@seasonal.sa",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Annual vs monthly billing — price difference?",
    body: "I'm currently monthly at $59/mo. How much would I save switching to annual billing? Do I get a refund on my current month?",
    fromName: "Tanya Ostrova",
    fromEmail: "tanya.ostrova@gmail.com",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(12),
  },
  {
    subject: "Can I white-label the product for our clients?",
    body: "We're a reseller and want to offer your platform under our own brand. Do you have a white-label or OEM program?",
    fromName: "Stefan Brandt",
    fromEmail: "stefan.brandt@resellergmbh.de",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(4),
  },
  {
    subject: "Account ownership transfer",
    body: "Our CTO who created the account is leaving the company. How do we transfer ownership to another admin without losing any data?",
    fromName: "Nina Volkov",
    fromEmail: "nina.volkov@techstartup.ru",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "Are you SOC 2 certified?",
    body: "Our procurement team requires SOC 2 Type II certification before we can sign off on this vendor. Can you share your latest report?",
    fromName: "David Nguyen",
    fromEmail: "d.nguyen@enterprise.com",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(9),
  },
  {
    subject: "What's your uptime SLA?",
    body: "Before committing to an annual contract, I need to understand your uptime guarantees and what happens if you miss the SLA.",
    fromName: "Amelia Hughes",
    fromEmail: "amelia.hughes@criticalops.com",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(35),
  },
  {
    subject: "How many API calls does my plan include?",
    body: "I'm on Pro and couldn't find the API call limit in the pricing page. Can you confirm the exact limit and what happens if we exceed it?",
    fromName: "Kofi Mensah",
    fromEmail: "kofi.mensah@apistartup.gh",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "Support hours and response times",
    body: "What are your standard support hours? We're in APAC (UTC+8) and want to know if we'd get same-day responses to critical issues.",
    fromName: "Wei Zhang",
    fromEmail: "wei.zhang@company.cn",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(28),
  },
  {
    subject: "Can we get a custom contract?",
    body: "We have specific legal requirements around liability and IP ownership. Is it possible to negotiate a custom master service agreement?",
    fromName: "Isabella Romano",
    fromEmail: "isabella.r@lawfirm.it",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(3),
  },
  {
    subject: "Multi-region data residency options",
    body: "We have customers in both the EU and US. Can our data be split by region, or is it all stored in one location?",
    fromName: "Tobias Weber",
    fromEmail: "tobias.weber@globalco.de",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "How to delete my account permanently",
    body: "I want to delete my account and all associated data under GDPR right to erasure. What's the process and how long does it take?",
    fromName: "Ewa Kowalczyk",
    fromEmail: "ewa.kowalczyk@email.pl",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(16),
  },
  {
    subject: "Partner program inquiry",
    body: "We're a consultancy that recommends tools to our clients. Do you have a referral or partner program with revenue sharing?",
    fromName: "Bongani Zulu",
    fromEmail: "bongani@consultza.co.za",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(5),
  },
  {
    subject: "Requesting invoice for tax purposes",
    body: "We need a proper VAT invoice for our subscription payments from the last 12 months for our annual tax filing. Can you send them to our accounting department?",
    fromName: "Sven Andersen",
    fromEmail: "sven.andersen@nordicco.dk",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(8),
  },

  // More technical questions
  {
    subject: "Rate limiting strategy for background jobs",
    body: "We have a nightly batch job that makes ~50k API calls. What's the best strategy to stay within rate limits without stretching the job too long?",
    fromName: "Aaron Fletcher",
    fromEmail: "aaron.f@dataengineering.com",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "React SDK not working with Next.js App Router",
    body: "The React SDK works fine in Pages Router but throws hydration errors in App Router. Is there a server-component compatible version in the works?",
    fromName: "Mia Chen",
    fromEmail: "mia.chen@nextjsdev.com",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "Terraform provider resource drift",
    body: "The Terraform provider reports drift every plan even when no changes have been made. It seems to be re-ordering a list field. Known issue?",
    fromName: "Jake Morrison",
    fromEmail: "jake.morrison@devops.io",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(17),
  },
  {
    subject: "SAML assertion not being accepted",
    body: "Setting up SAML SSO with Azure AD. The assertion is signed but we keep getting 'Invalid signature'. Our cert is SHA-256. Any common gotchas?",
    fromName: "Olga Petrov",
    fromEmail: "olga.petrov@corp.ru",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Bulk delete via API returning 413",
    body: "Sending a bulk delete request with 500 IDs returns HTTP 413 Payload Too Large. What's the max batch size for bulk operations?",
    fromName: "Tariq Hussain",
    fromEmail: "tariq.h@operations.pk",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    subject: "Audit log not capturing certain events",
    body: "Our audit log shows login events but not data export events. Is there a separate setting to enable export logging or is it a bug?",
    fromName: "Claire Fontaine",
    fromEmail: "claire.fontaine@compliance.fr",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(10),
  },
  {
    subject: "Python SDK throwing SSL verify errors behind proxy",
    body: "On our corporate network behind a proxy, the Python SDK throws ssl.SSLCertVerificationError. Is there a way to pass a custom CA bundle?",
    fromName: "Hiroshi Yamamoto",
    fromEmail: "hiroshi.yamamoto@corpjapan.jp",
    status: TicketStatus.closed,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(32),
  },
  {
    subject: "Database connection pool exhaustion under load",
    body: "Under load our integration times out with 'connection pool exhausted'. We're using the default pool size. What's the recommended pool configuration for high-traffic use?",
    fromName: "Mateus Costa",
    fromEmail: "mateus.costa@backend.br",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Custom domain SSL certificate not provisioning",
    body: "I added my custom domain 24 hours ago and the SSL certificate still shows as 'pending'. DNS records are correctly pointing to your servers.",
    fromName: "Zara Ahmed",
    fromEmail: "zara.ahmed@mybrand.pk",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Real-time updates not working with reverse proxy",
    body: "WebSocket connections for real-time updates fail when routed through our nginx reverse proxy. Standard HTTP works fine. Do you have a recommended nginx config?",
    fromName: "Anders Svensson",
    fromEmail: "anders.s@infra.se",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(19),
  },

  // More refund requests
  {
    subject: "Team seat refund — employee left",
    body: "One of our licensed users resigned last month. We've already removed their access but are still paying for their seat. Can we get a prorated refund?",
    fromName: "Paul Eriksson",
    fromEmail: "paul.eriksson@team.fi",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(4),
  },
  {
    subject: "Charged wrong tier price",
    body: "I signed up for the Starter plan at $19/mo but was charged $49/mo (Pro rate). Please correct and refund the difference.",
    fromName: "Diana Lee",
    fromEmail: "diana.lee@startup.sg",
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(6),
  },
  {
    subject: "Refund for training sessions not delivered",
    body: "We paid for 5 onboarding training sessions. Only 2 were delivered before our contact at your company left. Requesting refund for the 3 unused sessions.",
    fromName: "Fernando Castillo",
    fromEmail: "fernando.c@enterprise.mx",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(2),
  },
  {
    subject: "Renewal charge after downgrade request",
    body: "I submitted a downgrade request before my renewal date but was charged at the old rate. Please apply the downgrade and refund the price difference.",
    fromName: "Nneka Obi",
    fromEmail: "nneka.obi@smallbusiness.ng",
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(0),
  },
  {
    subject: "Currency conversion dispute",
    body: "I'm in Canada and was charged in USD without being clearly informed. The exchange rate used was significantly unfavorable. I'd like a partial refund for the difference.",
    fromName: "Marc Tremblay",
    fromEmail: "marc.tremblay@qc.ca",
    status: TicketStatus.closed,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(40),
  },

  // Uncategorized / null category
  {
    subject: "Login page not loading",
    body: "The login page just shows a blank white screen. This is happening on Chrome and Safari. Edge works fine. Urgent.",
    fromName: "Ryan O'Connor",
    fromEmail: "ryan.oconnor@agency.ie",
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "Dashboard takes 30+ seconds to load",
    body: "Since yesterday our dashboard is extremely slow. The spinner runs for over 30 seconds before the page loads. Other pages seem fine.",
    fromName: "Valentina Cruz",
    fromEmail: "valentina.cruz@mediahouse.co",
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Cannot access account — locked out",
    body: "I've been locked out of my account after too many failed attempts. Password reset emails are not arriving. I need access restored urgently.",
    fromName: "Omar Farouk",
    fromEmail: "omar.farouk@trading.eg",
    status: TicketStatus.resolved,
    category: null,
    createdAt: daysAgo(5),
  },
  {
    subject: "Notification emails going to spam",
    body: "All emails from your system are going directly to our spam folder. We've added your domain to the safe sender list but it keeps happening.",
    fromName: "Lisa Johansson",
    fromEmail: "lisa.j@nonprofit.se",
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(3),
  },
  {
    subject: "Data not syncing between mobile and web",
    body: "Records I create on mobile don't appear on the web app for several hours. Is there a manual sync option?",
    fromName: "Emre Yilmaz",
    fromEmail: "emre.yilmaz@consultant.tr",
    status: TicketStatus.closed,
    category: null,
    createdAt: daysAgo(45),
  },
  {
    subject: "Accessibility issues with screen reader",
    body: "Our visually impaired team member reports that the main navigation is not accessible via screen reader. Buttons are missing aria-labels.",
    fromName: "Anna Bergman",
    fromEmail: "anna.bergman@inclusion.se",
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: "Print layout is broken",
    body: "When printing reports the right side gets cut off regardless of the printer or paper size. Happens on all browsers.",
    fromName: "Kevin Walsh",
    fromEmail: "kevin.walsh@printshop.ie",
    status: TicketStatus.resolved,
    category: null,
    createdAt: daysAgo(14),
  },
  {
    subject: "Unexpected logout while working",
    body: "I keep getting logged out mid-session, sometimes after just 10 minutes. I haven't changed any security settings. This is very disruptive.",
    fromName: "Yuna Park",
    fromEmail: "yuna.park@designco.kr",
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Dark mode not saving preference",
    body: "I switch to dark mode but every time I open a new tab it reverts to light mode. This happens even when I'm logged in.",
    fromName: "Marco Esposito",
    fromEmail: "marco.esposito@dev.it",
    status: TicketStatus.closed,
    category: null,
    createdAt: daysAgo(22),
  },
  {
    subject: "Browser extension conflict",
    body: "Your app breaks when my uBlock Origin extension is active. I've disabled it on your domain but some assets still fail to load.",
    fromName: "Ingrid Holm",
    fromEmail: "ingrid.holm@freelance.no",
    status: TicketStatus.resolved,
    category: null,
    createdAt: daysAgo(11),
  },

  // More general and technical mix
  {
    subject: "Backup and restore documentation unclear",
    body: "The docs mention automatic backups but don't explain how to restore. Can you walk me through restoring from a specific point in time?",
    fromName: "Chukwuma Eze",
    fromEmail: "chukwuma.eze@techfirm.ng",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    subject: "Locale settings not applying to date formats",
    body: "I've set my locale to en-GB but dates still display in MM/DD/YYYY format instead of DD/MM/YYYY. Is this a known issue?",
    fromName: "Patrick Murphy",
    fromEmail: "p.murphy@contractor.ie",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(8),
  },
  {
    subject: "How do I set up role-based access control?",
    body: "We want some users to only view reports while others can also edit data. Is there a built-in RBAC system or do we need to manage permissions manually?",
    fromName: "Priscilla Santos",
    fromEmail: "priscilla.santos@corp.br",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "Migration from legacy system — help needed",
    body: "We're moving from a 10-year-old on-premise system. Do you offer a migration service or consulting to help move our 2 million records over?",
    fromName: "Henrik Larsen",
    fromEmail: "henrik.larsen@oldschool.dk",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Two accounts merged — data missing",
    body: "I had a personal and a work account and your team merged them last week. Now several months of data from the personal account appears to be missing.",
    fromName: "Alice Fontaine",
    fromEmail: "alice.fontaine@professional.fr",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "Invoice payment failed — card declined",
    body: "Our autopay failed this month. I've updated the card details but the system still shows the invoice as unpaid. Can you trigger a manual retry?",
    fromName: "Thomas Gruber",
    fromEmail: "thomas.gruber@business.at",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(6),
  },
  {
    subject: "Scheduled report not being sent",
    body: "I configured a weekly summary report to email every Monday at 9am. It worked for 3 weeks then stopped. No changes were made to the schedule.",
    fromName: "Chiara Ricci",
    fromEmail: "chiara.ricci@analytics.it",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(4),
  },
  {
    subject: "Can I use my own storage bucket?",
    body: "For compliance we need to store uploaded files in our own S3 bucket. Is bring-your-own-storage supported on any plan?",
    fromName: "Dmitri Volkov",
    fromEmail: "dmitri.volkov@cloud.ru",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "Onboarding checklist never completes",
    body: "I've completed all the steps in the onboarding checklist but step 4 'Connect your first integration' stays unchecked even after connecting Slack.",
    fromName: "Fatou Diop",
    fromEmail: "fatou.diop@startup.sn",
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(9),
  },
  {
    subject: "Support for Arabic RTL layout",
    body: "We serve Arabic-speaking users and the UI completely breaks with RTL text direction. Is RTL support on the roadmap?",
    fromName: "Layla Hassan",
    fromEmail: "layla.hassan@arabicsite.ae",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Integration with HubSpot CRM",
    body: "Is there a native HubSpot integration? I want contact data to sync bidirectionally. If not native, is there a documented way to do it via API?",
    fromName: "Michael Bauer",
    fromEmail: "michael.bauer@sales.de",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    subject: "Compliance report export broken",
    body: "The 'Export Compliance Report' button gives a 500 error. This is blocking our quarterly audit submission due in 48 hours. Please escalate.",
    fromName: "Rebecca Stone",
    fromEmail: "r.stone@financefirm.com",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "Feature request: bulk user import via CSV",
    body: "We have 200 users to add and adding them one by one is impractical. Is bulk CSV import on the roadmap for user management?",
    fromName: "Lucas Fernandez",
    fromEmail: "lucas.f@hr.ar",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(60),
  },
  {
    subject: "Trial account expired but still evaluating",
    body: "Our trial ended but our procurement cycle takes 6 weeks. Can you extend the trial by 3 weeks while we complete the approval process?",
    fromName: "Soo-Jin Lim",
    fromEmail: "soojin.lim@corp.kr",
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(15),
  },
  {
    subject: "Unexpected data deletion — need recovery",
    body: "A team member accidentally deleted a project containing 6 months of data. Is there any way to recover it? We're willing to pay for data recovery services.",
    fromName: "Andrei Popescu",
    fromEmail: "andrei.popescu@agency.ro",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(0),
  },
  {
    subject: "How to transfer data between workspaces",
    body: "We have data split across two workspaces from a past restructure. What's the recommended way to consolidate everything into one workspace?",
    fromName: "Ingeborg Nilsen",
    fromEmail: "ingeborg.nilsen@corp.no",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "Requesting dedicated account manager",
    body: "We spend over $5k/month on your platform. Is it possible to get a dedicated account manager or named support contact for our team?",
    fromName: "Jonathan Park",
    fromEmail: "jonathan.park@bigclient.com",
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    subject: "Refund — purchased wrong plan type",
    body: "I purchased the individual plan but I actually need the team plan. I only noticed after payment. Can I switch and apply what I paid toward the team plan?",
    fromName: "Carine Lefevre",
    fromEmail: "carine.lefevre@solo.fr",
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(7),
  },
  {
    subject: "Localization missing for Japanese",
    body: "The app is partially translated into Japanese but several key screens (settings, billing) are still in English. When will full Japanese localization be available?",
    fromName: "Kenji Watanabe",
    fromEmail: "kenji.watanabe@jpuser.jp",
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(50),
  },
  {
    subject: "Performance regression in v4.2 update",
    body: "After updating to v4.2 last Tuesday, list views that used to load in <1s now take 5-8 seconds. Rolling back to v4.1 resolves it. Is this a known regression?",
    fromName: "Elisa Conti",
    fromEmail: "elisa.conti@devteam.it",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    subject: "Credit card update not saving",
    body: "Every time I try to update my payment method the page says 'Card saved' but the old card is still shown when I refresh. Tried 3 different browsers.",
    fromName: "Samuel Osei",
    fromEmail: "samuel.osei@business.gh",
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
];

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(
    Math.floor(Math.random() * 10) + 8,
    Math.floor(Math.random() * 60),
    0,
    0,
  );
  return d;
}

async function main() {
  console.log(`Seeding ${tickets.length} tickets...`);
  const result = await prisma.ticket.createMany({ data: tickets });
  console.log(`Created ${result.count} tickets.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
